library(shiny)
shinyUI(
  pageWithSidebar(
    # Application title 
    headerPanel("March Madness 2015"),
    sidebarPanel(
      selectInput(inputId = "teamA",
                  label = "Your matchup: Select Team A 
                  (occurring before Team B alphabetically)",
                  choices = c("Albany NY",
                              "Arizona",
                              "Arkansas",
                              "Baylor",
                              "Belmont",
                              "Boise St",
                              "Buffalo",
                              "Butler",
                              "BYU",
                              "Cincinnati",
                              "Coastal Car",
                              "Davidson",
                              "Dayton",
                              "Duke",
                              "E Washington",
                              "Georgetown",
                              "Georgia",
                              "Georgia St",
                              "Gonzaga",
                              "Hampton",
                              "Harvard",
                              "Indiana",
                              "Iowa",
                              "Iowa St",
                              "Kansas",
                              "Kentucky",
                              "Lafayette",
                              "Louisville",
                              "LSU",
                              "Manhattan",
                              "Maryland",
                              "Michigan St",
                              "Mississippi",
                              "N Dakota St",
                              "NC State",
                              "New Mexico St",
                              "North Carolina",
                              "North Florida",
                              "Northeastern",
                              "Northern Iowa",
                              "Notre Dame",
                              "Ohio St",
                              "Oklahoma",
                              "Oklahoma St",
                              "Oregon",
                              "Providence",
                              "Purdue",
                              "Robert Morris",
                              "San Diego St",
                              "SF Austin",
                              "SMU",
                              "St John's",
                              "Texas",
                              "TX Southern",
                              "UAB",
                              "UC Irvine",
                              "UCLA",
                              "Utah",
                              "VA Commonwealth",
                              "Valparaiso",
                              "Villanova",
                              "Virginia",
                              "West Virginia",
                              "Wichita St",
                              "Wisconsin",
                              "Wofford",
                              "Wyoming"),
                  selected = "Dayton"),
      selectInput(inputId = "teamB",
                  label = "Select Team B
                  (occurring after Team A alphabetically)",
                  choices = c("Arizona",
                              "Arkansas",
                              "Baylor",
                              "Belmont",
                              "Boise St",
                              "Buffalo",
                              "Butler",
                              "BYU",
                              "Cincinnati",
                              "Coastal Car",
                              "Davidson",
                              "Dayton",
                              "Duke",
                              "E Washington",
                              "Georgetown",
                              "Georgia",
                              "Georgia St",
                              "Gonzaga",
                              "Hampton",
                              "Harvard",
                              "Indiana",
                              "Iowa",
                              "Iowa St",
                              "Kansas",
                              "Kentucky",
                              "Lafayette",
                              "Louisville",
                              "LSU",
                              "Manhattan",
                              "Maryland",
                              "Michigan St",
                              "Mississippi",
                              "N Dakota St",
                              "NC State",
                              "New Mexico St",
                              "North Carolina",
                              "North Florida",
                              "Northeastern",
                              "Northern Iowa",
                              "Notre Dame",
                              "Ohio St",
                              "Oklahoma",
                              "Oklahoma St",
                              "Oregon",
                              "Providence",
                              "Purdue",
                              "Robert Morris",
                              "San Diego St",
                              "SF Austin",
                              "SMU",
                              "St John's",
                              "Texas",
                              "TX Southern",
                              "UAB",
                              "UC Irvine",
                              "UCLA",
                              "Utah",
                              "VA Commonwealth",
                              "Valparaiso",
                              "Villanova",
                              "Virginia",
                              "West Virginia",
                              "Wichita St",
                              "Wisconsin",
                              "Wofford",
                              "Wyoming",
                              "Xavier"),
                  selected = "Providence"),
      checkboxInput(inputId = "predicted_outcome",
                    label = strong("Show predicted outcome"),
                    value = FALSE),
      checkboxInput(inputId = "actual_outcome",
                    label = strong("Show actual outcome"),
                    value = FALSE),
      submitButton('Submit')
    ),
    mainPanel(h3('Results'),
              h4('The favorite for this matchup was:'),
              verbatimTextOutput("pred_team"),
              h4('The winner of this matchup was:'),
              verbatimTextOutput("winning_team")
              )
  )
)